title: "fighting-game-button-challenge"
description: "fighting-game-button-challenge"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/fighting-game-button-challenge
